### ISSUE TITLE
NullPointerException when externs for superclass are missing

### ISSUE THREAD

**Issue by rehmsen** [angular/clutz#264]
I ran Clutz on a dependency that apparently does not have its externs set up properly (which I will look to fix) and an NPE was thrown:

```
java.lang.NullPointerException
at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.aggregateFieldsFromClass(DeclarationGenerator.java:1487)
at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.getSuperClassFields(DeclarationGenerator.java:1473)
at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.visitObjectType(DeclarationGenerator.java:1423)
at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.visitClassOrInterface(DeclarationGenerator.java:1021)
at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.walk(DeclarationGenerator.java:858)
at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.access$100(DeclarationGenerator.java:795)
at com.google.javascript.clutz.DeclarationGenerator.declareNamespace(DeclarationGenerator.java:494)
at com.google.javascript.clutz.DeclarationGenerator.produceDts(DeclarationGenerator.java:275)
at com.google.javascript.clutz.DeclarationGenerator.generateDeclarations(DeclarationGenerator.java:207)
at com.google.javascript.clutz.DeclarationGenerator.generateDeclarations(DeclarationGenerator.java:183)
at com.google.javascript.clutz.DeclarationGenerator.main(DeclarationGenerator.java:124)

```
I added some print statements and apparently it is superClass.getConstructor() which is null, and when I print superClass I just get "?".
Should probably avoid crashing in such a situation.

**Comment by rehmsen** [comment]
Ran into this again, this time the line numbers were slightly different so I provide them here again to make debugging easier:

    java.lang.NullPointerException
      at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.aggregateFieldsFromClass(DeclarationGenerator.java:1633)
      at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.getSuperClassFields(DeclarationGenerator.java:1619)
      at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.visitObjectType(DeclarationGenerator.java:1565)
      at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.visitClassOrInterface(DeclarationGenerator.java:1141)
      at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.walk(DeclarationGenerator.java:977)
      at com.google.javascript.clutz.DeclarationGenerator$TreeWalker.access$200(DeclarationGenerator.java:914)
      at com.google.javascript.clutz.DeclarationGenerator.declareNamespace(DeclarationGenerator.java:602)
      at com.google.javascript.clutz.DeclarationGenerator.produceDts(DeclarationGenerator.java:307)
      at com.google.javascript.clutz.DeclarationGenerator.generateDeclarations(DeclarationGenerator.java:236)
      at com.google.javascript.clutz.DeclarationGenerator.generateDeclarations(DeclarationGenerator.java:217)
      at com.google.javascript.clutz.DeclarationGenerator.main(DeclarationGenerator.java:140)
    Uncaught exception in clutz, exiting.

**Comment by mprobst** [comment]
FYI Rado is at ngconf, this will have to wait 'til after Monday.

**Comment by rkirov** [comment]
This was fixed with more aggressive null checks:
https://github.com/angular/clutz/blob/master/src/main/java/com/google/javascript/clutz/DeclarationGenerator.java#L1814
