### ISSUE TITLE
ConcurrentModificationException when adding externs

### ISSUE THREAD

**Issue by rehmsen** [angular/clutz#266]
I added an gen_js_externs rule to the externs_list property of a ts_library rule, and am consistently getting:

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:902)
	at java.util.ArrayList$Itr.next(ArrayList.java:852)
	at com.google.javascript.clutz.DeclarationGenerator.processExternSymbols(DeclarationGenerator.java:385)
	at com.google.javascript.clutz.DeclarationGenerator.produceDts(DeclarationGenerator.java:286)
	at com.google.javascript.clutz.DeclarationGenerator.generateDeclarations(DeclarationGenerator.java:207)
	at com.google.javascript.clutz.DeclarationGenerator.generateDeclarations(DeclarationGenerator.java:183)
	at com.google.javascript.clutz.DeclarationGenerator.main(DeclarationGenerator.java:124)
```

I am not a Java expert, but I guess you cannot remove elements from an array you iterate over:
```
  for (TypedVar symbol : externSymbols) {
      if (enumElementSymbols.contains(symbol.getName())) {
        externSymbols.remove(symbol);
      }
   }
```

That code was added in 
https://github.com/angular/clutz/commit/670be44650a5a96fa579f979bdd6bd732c17ea97

Could I really be the first to hit that code path?
I can send a PR with the fix.

**Comment by rehmsen** [comment]
https://github.com/angular/clutz/pull/267

**Comment by mprobst** [comment]
#267 fixes the immediate issue, but the larger problem is that we need a test to cover this.

**Comment by rkirov** [comment]
Added a breakpoint at the `it.remove()` line added by Ole and they are hit by `extern_enum.externs.js`. The file is pretty simple enum in externs, so I am considering it a fine test coverage.
