### ISSUE TITLE
NullPointerException when encountering namespaced `Object` typedef

### ISSUE THREAD

**Issue by rafaelweinstein** [angular/clutz#771]
foo.js:
```
const foo = {};

/**
 * @constructor
 */
foo.Bar = function() {
};

/**
 * @typedef {{
 *   baz: string,
 * }}
 */
foo.Bar.Bat;
```

processed via `./build/install/clutz/bin/gents --convert foo.js -o out`

outputs:
```
java.lang.NullPointerException
	at com.google.javascript.gents.TypeConversionPass.convertTypeAlias(TypeConversionPass.java:473)
	at com.google.javascript.gents.TypeConversionPass.process(TypeConversionPass.java:69)
	at com.google.javascript.gents.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:192)
	at com.google.javascript.gents.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:121)
	at com.google.javascript.gents.TypeScriptGenerator.main(TypeScriptGenerator.java:75)
Uncaught exception in gents, exiting.
```

**Comment by rafaelweinstein** [comment]
cc @evmar

**Comment by evmar** [comment]
Hm that stack trace points into a comment:
https://github.com/angular/clutz/blob/9856fbe08e3c8c59724201255868b08fa34f7859/src/main/java/com/google/javascript/gents/TypeConversionPass.java#L473

cc @bowenni does this mean anything to you?
