### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by donmccurdy** [angular/clutz#772]
node: 8.11.4
npm: 5.6.0
gradle: 4.9
os: MacOS 10.13.6

```
> Task :test
objc[34797]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java (0x10b2a94c0) and /Li
brary/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10b3354e0). One of the two will be used. Which one is undefin
ed.

com.google.javascript.clutz.DeclarationSyntaxTest > testDeclarationUsage FAILED
    java.lang.AssertionError: tsc exited abnormally with code 1
    src/test/java/com/google/javascript/clutz/reserved_var_names.d.ts(6,18): error TS2503: Cannot find namespace 'a'.
    src/test/java/com/google/javascript/clutz/reserved_var_names.d.ts(10,18): error TS2503: Cannot find namespace 'switch_'.
        at org.junit.Assert.fail(Assert.java:88)
        at com.google.javascript.clutz.DeclarationSyntaxTest.runChecked(DeclarationSyntaxTest.java:138)
        at com.google.javascript.clutz.DeclarationSyntaxTest.doTestDeclarationUsage(DeclarationSyntaxTest.java:126)
        at com.google.javascript.clutz.DeclarationSyntaxTest.testDeclarationUsage(DeclarationSyntaxTest.java:113)

237 tests completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/donmccurdy/Documents/Projects/clutz/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 46s
8 actionable tasks: 8 executed
```

**Comment by rkirov** [comment]
I think it is the same issue as described here https://github.com/angular/clutz/issues/594#issuecomment-387573566 

It passes on CI because the order of the files is different (I haven't verified). The solution is upgrading to TS 3.0.

**Comment by donmccurdy** [comment]
Thanks, I've confirmed it builds after updating typescript, so +1 for #778. :)
